version: '2'
services:
  php-apache-dev:
    build: .
    ports:
      - '7888:80'
      - '32770:3333'
    environment: []
    volumes:
      - '/home/eduard/Project/test_kohana:/app'
    links:
      - postgresql
      - gearmand
  postgresql:
    image: mkurnikov/postgresql-9.4
    environment:
      - POSTGRES_PASSWORD=123qwe
  gearmand:
    image: artefactual/gearmand
  ubuntu-gearman-worker-php:
    image: lysender/ubuntu-gearman-worker-php
    links:
      - gearmand
